### ISSUE TITLE
How to Change Temperature in CC-CV

### ISSUE THREAD

**Issue by lico0001** [MarcBerliner/PETLION.jl#100]
Hello MarcBerliner, how to simulate under different battery temperature and ambient temperature, and whether there is a relevant input parameter interface？ 
If there is no such interface, can the simulation be performed by modifying these two temperatures in the PETLION source code? Are the simulation results obtained after this modification accurate?
Looking forward to your reply, thanks.

**Comment by MarcBerliner** [comment]
You can specify the initial temperature (or the constant temperature if run isothermally) with `p.θ[:T₀] = 25+273.15` and the ambient temperature with `p.θ[:T_amb] = 25+273.15`.

**Comment by lico0001** [comment]
Thank you MarcBerliner. Got it.

**Comment by lico0001** [comment]
Thank you MarcBerliner. Got it.
