### ISSUE TITLE
 Error in fast_charging_CC-CT-CV

### ISSUE THREAD

**Issue by lico0001** [MarcBerliner/PETLION.jl#104]
Excuse me.  When I use the example 'fast_charging_CC-CT-CV', it while raises the  ERROR:
--------
  Invalid keyword argument: dT

  Choose one from: (I, P, V)

at this pharaph: simulate!(sol, p, dT=:hold) # equivalent to `simulate!(sol, p, dT=0)`
 So how can I run it? THANKS.

**Comment by MarcBerliner** [comment]
Make sure your PETLION package is up to date with `import Pkg; Pkg.update()`. Constant temperature only works on v1.0.0 and v1.0.1
