### ISSUE TITLE
type of the battery

### ISSUE THREAD

**Issue by mooncode30** [MarcBerliner/PETLION.jl#105]
hi marcberliner, 
I wanna ask, is this open source petlion only for lithium-ion batteries? can other types of batteries such as lithium-polymer use this petlion?

**Comment by MarcBerliner** [comment]
PETLION only supports lithium-ion, not lithium-polymer.

**Comment by mooncode30** [comment]
even though the electrodes from Li-Po are the same as lithium ion, namely using LCO, can it still not be used for lithium polymer battery models?

**Comment by MarcBerliner** [comment]
Can you share a paper with the PDEs describing lithium-polymer dynamics?
