### ISSUE TITLE
error array

### ISSUE THREAD

**Issue by mooncode30** [MarcBerliner/PETLION.jl#107]
hello sir, can u help me to solve this problem?
![image](https://github.com/MarcBerliner/PETLION.jl/assets/132383791/ec564113-363e-4ed7-8800-09e8d510a7c1)

**Comment by MarcBerliner** [comment]
What version of PETLION are you using? I released a couple of updates addressing this issue with Sundials.jl. Please update your PETLION package using `import Pkg; Pkg.update()` and try again.

**Comment by MarcBerliner** [comment]
I believe your environment is using the old version of PETLION. Try restarting Julia and running `import Pkg; Pkg.status()`. Make sure PETLION is v1.0.3, and then try running the example.

**Comment by mooncode30** [comment]
the version of petlion already is v1.0.3, but still error with the type Array
![image](https://github.com/MarcBerliner/PETLION.jl/assets/132383791/a0648c5d-4217-4614-81c6-30fd7bab7d34)

**Comment by MarcBerliner** [comment]
And you've restarted Julia?

Please post the entire stacktrace.

**Comment by mooncode30** [comment]
hi sir, i wanna ask again.
i wanna know the reason why in graph both state of health and state of charge is (-) ?
![image](https://github.com/MarcBerliner/PETLION.jl/assets/132383791/faeff747-142d-4c19-b3dd-f57644dda14f)
