### ISSUE TITLE
Variable current input - discrete current table?

### ISSUE THREAD

**Issue by hjli528** [MarcBerliner/PETLION.jl#85]
Thanks for sharing the code. 

I have one question, looks like the variable current input does not support discrete time-current table, is there a plan to add this in the future? so should I just wrap a lookup function in the I_fun and pass it to the solver?

Thanks,

**Comment by MarcBerliner** [comment]
Hello,

It seems like wrapping the lookup function in I_fun(t) is probably the simplest choice here (check out example 1 in the [variable_input_functions.ipynb](https://github.com/MarcBerliner/PETLION.jl/blob/master/examples/variable_input_functions.ipynb) if you haven't already).

If that doesn't address your question, feel free to leave a followup with a minimal example of your setup.

Best,
Marc
