### ISSUE TITLE
 the decay of battery capacity

### ISSUE THREAD

**Issue by steal-the-soul** [MarcBerliner/PETLION.jl#89]
Thanks for sharing the code.

I have one question, When creating a battery model, is it possible to simulate the decay of battery capacity through hundreds of charge and discharge cycles?

Thanks,

**Comment by MarcBerliner** [comment]
Hi,

Yes, that is handled through the keyword argument `aging` to the `Params` function. For example, to enable a lithium plating side reaction degradation model with LCO chemistry run `p = Params(LCO; aging=:SEI)`.

After evaluating the model, you can find state-of-health (SOH) by `model.SOH` and similarly calculate the fractional capacity fade by `1-model.SOH`.

I just pushed a minor update, so be sure to update your packages before trying it out!

Best,
Marc

**Comment by steal-the-soul** [comment]
Great! Thanks a lot for your help. I wish you good health and smooth work.
