### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by steal-the-soul** [MarcBerliner/PETLION.jl#91]
Hi,

Yes, that is handled through the keyword argument `aging` to the `Params` function. For example, to enable a lithium plating side reaction degradation model with LCO chemistry run `p = Params(LCO; aging=:SEI)`.

After evaluating the model, you can find state-of-health (SOH) by `model.SOH` and similarly calculate the fractional capacity fade by `1-model.SOH`.

I just pushed a minor update, so be sure to update your packages before trying it out!

Best,
Marc

_Originally posted by @MarcBerliner in https://github.com/MarcBerliner/PETLION.jl/issues/89#issuecomment-1000899127_

**Comment by MarcBerliner** [comment]
Duplicate #92
