### ISSUE TITLE
State new created with wrong discretization for D_s_eff?

### ISSUE THREAD

**Issue by muendlein** [MarcBerliner/PETLION.jl#96]
It seems like that the `build_D_s_eff` function use the wrong discretization.
https://github.com/MarcBerliner/PETLION.jl/blob/6cd010444812241504df021e89384f8a1a3f24fd/src/physics_equations/auxiliary_states_and_coefficients.jl#L348

Unless I am overlooking something the section argument should take `r_p` and `r_n` as `build_D_s_eff` refers to the solid diffusion (in the particle).

`states[:D_s_eff] = state_new(D_s_eff, (:p, :n), p)` -> `states[:D_s_eff] = state_new(D_s_eff, (:r_p, :r_n), p)`

**Comment by MarcBerliner** [comment]
I modeled the governing equations after [LIONSIMBA](https://github.com/lionsimbatoolbox/LIONSIMBA), which assumes the solid diffusion only varies in the $x$-direction and takes the value to be constant using the solid particle surface concentration and temperature. It is certainly possible to modify the code to make $D_{\mathrm{eff},s}$ a function of $x$ and $r$, but with the given assumption, the current implementation is correct.
